#!/usr/bin/env python
import sys
import subprocess


def run_server():
    try:
        port = sys.argv[1]
        subprocess.call("python manage.py runserver {}".format(port))
    except:
        raise AttributeError("Port must be specified and must be a number")


run_server()
