#!/usr/bin/env python
import os
import sys
import subprocess

if __name__ == "__main__":
    try:
        if len(sys.argv) == 1:
            subprocess.call("python manage.py runserver {}".format(
                os.getenv('PORT') or 8000))
        subprocess.call("python manage.py runserver {}".format(sys.argv[1]))
    except KeyboardInterrupt:
        print("Server has been shutdown")
